project:
  type: book

book:
  title: "Medical Device Systems Engineering Knowledge Repository Report"
  author:
    - name: "Esteban Solorzano"
      url: https://soloesteban.github.io/masters_stevens/
      email: esteban.solorzano@gmail.com
      affiliation: 
      - name: Stevens Institute of Technology
        city: Hoboken
        state: NJ
        url: www.stevens.edu
  date: "4/24/2024"
  downloads: pdf
  sharing: linkedin
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - background.qmd
    - methodology.qmd
    - problem.qmd
    - mission.qmd
    - sources.qmd
    - survey_results.qmd
    - stakeholders.qmd
    - goals_objectives.qmd
    - operational_analysis.qmd
    - physical_architecture.qmd
    - system_req.qmd
    - conclusions.qmd
    - references.qmd
  appendices:
    - survey.qmd
    - standards.qmd
    - definitions.qmd
    - risks.qmd
    - job_descriptions.qmd
  sidebar:
    logo: logoMedSE.jpg

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



