project:
  type: book

book:
  title: "Medical Device Systems Engineering Knowledge Repository Report"
  author: "Esteban Solorzano"
  date: "4/21/2024"
  downloads: pdf
  sharing: linkedin
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - background.qmd
    - methodology.qmd
    - problem.qmd
    - mission.qmd
    - sources.qmd
    - survey_results.qmd
    - stakeholders.qmd
    - goals_objectives.qmd
    - operational_analysis.qmd
    - physical_architecture.qmd
    - system_req.qmd
    - conclusions.qmd
    - references.qmd
  appendices:
    - survey.qmd
    - standards.qmd
    - definitions.qmd
    - risks.qmd
    - job_descriptions.qmd    


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



