---
title: "Terminology"
format: html
---

::: callout-caution
The report published on this website is a draft and subject to frequent updates. Please be aware that the content may change over time as revisions are made. Thank you for your understanding.
:::

::: callout-tip
If you have questions, comments, or feedback, please contact Esteban Solorzano.

[esteban.solorzano\@gmail.com](esteban.solorzano@gmail.com)
:::

::: {#tbl-definitions}
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Term           | Definition                                                                                                                                                                                                                         |
+================+====================================================================================================================================================================================================================================+
| 510(k)         | Premarket Notification                                                                                                                                                                                                             |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| AAMI           | Association for the Advancement of Medical Instrumentation                                                                                                                                                                         |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CAPA           | Corrective and Preventive Action                                                                                                                                                                                                   |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CDRH           | Center for Devices and Radiological Health                                                                                                                                                                                         |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CE Certificate | An acronym for the French “Conformite Europeenne” [@cemarki]                                                                                                                                                                       |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CFR            | Code of Federal Regulations                                                                                                                                                                                                        |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| FDA            | Food and Drug Administration                                                                                                                                                                                                       |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| FMEA           | Failure Modes and Effects Analysis                                                                                                                                                                                                 |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| GSPR           | General Safety and Performance Requirements                                                                                                                                                                                        |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| HACCP          | Hazard Analysis Critical Control Point [@nutrition2024]                                                                                                                                                                            |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| HFE            | Human Factors Engineering                                                                                                                                                                                                          |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| IEC            | International Electrotechnical Commission                                                                                                                                                                                          |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| IDE            | Integrated Development Environment                                                                                                                                                                                                 |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| INCOSE         | International Council on Systems Engineering                                                                                                                                                                                       |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ISO            | International Organization for Standardization                                                                                                                                                                                     |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| IVD            | In Vitro Diagnostic                                                                                                                                                                                                                |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| MDD            | Medical Device Directive (replaced by MDR)                                                                                                                                                                                         |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| MDLC           | Medical Device Development Life Cycle                                                                                                                                                                                              |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| MDR            | Medical Device Regulation (EU)                                                                                                                                                                                                     |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| MDSE           | Medical Device Systems Engineer                                                                                                                                                                                                    |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Medical device | Section 201(h) of the FD&C Act [@21usc3a] provides that the term "device" means:                                                                                                                                                   |
|                |                                                                                                                                                                                                                                    |
|                | an instrument, apparatus, implement, machine, contrivance, implant, in vitro reagent, or other similar or related article, including any component, part, or accessory, which is--                                                 |
|                |                                                                                                                                                                                                                                    |
|                | \(1\) recognized in the official National Formulary, or the United States Pharmacopeia, or any supplement to them,                                                                                                                 |
|                |                                                                                                                                                                                                                                    |
|                | \(2\) intended for use in the diagnosis of disease or other conditions, or in the cure, mitigation, treatment, or prevention of disease, in man or other animals, or                                                               |
|                |                                                                                                                                                                                                                                    |
|                | \(3\) intended to affect the structure or any function of the body of man or other animals, and                                                                                                                                    |
|                |                                                                                                                                                                                                                                    |
|                | which does not achieve its primary intended purposes through chemical action within or on the body of man or other animals and which is not dependent upon being metabolized for the achievement of its primary intended purposes. |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| MedSE          | Medical Device Systems Engineering                                                                                                                                                                                                 |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PMA            | Premarket Approval                                                                                                                                                                                                                 |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PMDA           | Pharmaceuticals and Medical Devices Agency                                                                                                                                                                                         |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| QA/QC          | Quality Assurance/Quality Control                                                                                                                                                                                                  |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| QMS            | Quality Management System                                                                                                                                                                                                          |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| QSR            | Quality System Regulations [@health2024a]                                                                                                                                                                                          |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| STEM           | Science, Technology, Engineering, and Math                                                                                                                                                                                         |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SysML          | Systems Modeling Language                                                                                                                                                                                                          |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| TRIZ           | Russian acronym for "Theory of Inventive Problem Solving" [@triz2024]                                                                                                                                                              |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| UDI            | Unique Device Identification                                                                                                                                                                                                       |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| V&V            | Verification and Validation                                                                                                                                                                                                        |
+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Definitions {.striped .hover}
:::