---
title: "Standards"
format: html
---

::: {.callout-caution}
The report published on this website is a draft and subject to frequent updates. Please be aware that the content may change over time as revisions are made. Thank you for your understanding.
:::

::: {.callout-tip}
If you have questions, comments, or feedback, please contact Esteban Solorzano.

[esteban.solorzano@gmail.com](esteban.solorzano@gmail.com)
:::


@tbl-standards shows a list of examples of standards and regulations relevant to medical device systems engineering.

::: {#tbl-standards}
|                   |                                                                                                                                                                                                                                                                                          |
|----------------|--------------------------------------------------------|
| **Reference**     | **Title**                                                                                                                                                                                                                                                                                |
| 21 CFR 820        | CFR - Code of Federal Regulations Title 21                                                                                                                                                                                                                                               |
| 21 USC 321        | Chapter 9-Federal Food, Drug, and Cosmetic Act Subchapter II-Definition                                                                                                                                                                                                                  |
| EN 45502-1        | Implants for surgery – Active Implantable Medical Devices – Part 1: General requirements for safety, marking and for information to be provided by the manufacturer                                                                                                                      |
| IEC 13485         | Medical devices — Quality management systems — Requirements for regulatory purposes                                                                                                                                                                                                      |
| ISO 14971         | Application of Risk Management to Medical Devices                                                                                                                                                                                                                                        |
| IEC 15288         | Systems and software engineering — System life cycle processes                                                                                                                                                                                                                           |
| IEC 60068-2-82    | Environmental Testing – Part 2-82: Tests – Test Tx: Whisker Test Methods for Electronic and Electric Components                                                                                                                                                                          |
| IEC 60601-1       | Medical electrical equipment – Part 1: General requirements for basic safety and essential performance                                                                                                                                                                                   |
| IEC 60601-1-2     | Medical electrical equipment – Part 1-2: General requirements for basic safety and essential performance – Collateral Standard: Electromagnetic disturbances – Requirements and tests                                                                                                    |
| IEC/TR 60601-4-2  | Medical electrical equipment - Part 4-2: Guidance and interpretation - Electromagnetic immunity: performance of medical electrical equipment and medical electrical systems                                                                                                              |
| IEC 60812:2018    | Failure modes and effects analysis (FMEA and FMECA)                                                                                                                                                                                                                                      |
| IEC 61025         | Fault Tree Analysis                                                                                                                                                                                                                                                                      |
| IEC 62304         | Medical Device Software - Software Life Cycle Processes                                                                                                                                                                                                                                  |
| IEC 62353         | Medical electrical equipment – Recurrent test and test after repair of medical electrical equipment                                                                                                                                                                                      |
| IEC 62366-1       | Medical devices – Part 1: Application of usability engineering to medical devices                                                                                                                                                                                                        |
| IEC DTR 60601-4-2 | Guidance and interpretation – Electromagnetic immunity: performance of medical electrical equipment and medical electrical systems                                                                                                                                                       |
| ISO 14971         | Medical devices - Application of risk management to medical devices                                                                                                                                                                                                                      |
| JEDEC/IPC JP002   | Current Tin Whisker Theory and Mitigations Practices Guideline                                                                                                                                                                                                                           |
| 2011/65/EU        | Directive 2011/65/EU of the European Parliament and of the Council of 8 June 2011 on the restriction of the use of certain hazardous substances in electrical and electronic equipment                                                                                                   |
| 2016/679          | Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (General Data Protection Regulation) |

Reference Standards and Regulations
:::